### ISSUE TITLE
案例分析部分下方答案栏无法独立上下滚动

### ISSUE THREAD

**Issue by 0xff06b5** [ruankaodaren/ruankao#10]
可以看出上下分栏是为了让题目区和答案区可以独立滚动，以实现题目和其对应答案同时出现在屏幕可见空间，但是目前题目区是可以独立上下滚动，但是答案区不行，在答案区使用鼠标滚轮向下滚动就会带着题目区一起滚动，导致屏幕可见部分只有答案区。

**Comment by xiaomabenten** [comment]
收到BUG反馈，最近安排优化

**Comment by ruankaodaren** [comment]
收到BUG反馈，最近安排优化

**Comment by ruankaodaren** [comment]
已上线
