### ISSUE TITLE
章节练习

### ISSUE THREAD

**Issue by likeitchen** [ruankaodaren/ruankao#14]
PC端后续是否可以支持章节练习呢
![1726134921677](https://github.com/user-attachments/assets/c8556fa7-57dd-4a62-aeac-f43743e3fef7)
![1726134958211](https://github.com/user-attachments/assets/c4da74c5-2720-4f48-9d03-2b276227fe95)

**Comment by ruankaodaren** [comment]
此功能已存在，首页往下滑动，就是章节练习
![45ca13e5e89f87c2a44b4998ea16482](https://github.com/user-attachments/assets/d04083a0-2e8f-4a83-8043-e31c2ebfdebe)
