### ISSUE TITLE
[Feature] 对"作答"分割线可以增加拖动需求

### ISSUE THREAD

**Issue by JYbill** [ruankaodaren/ruankao#2]
<img width="914" alt="image" src="https://github.com/user-attachments/assets/4326c7ce-32ef-43bf-a4b0-a61c771eefe5">

- 对于小屏用户来说，滚动有时候看有些题目时比较难受。我现在都是"右键" - "在新标签中打开图片"😄
- 刷题网站做的很强 👍

**Comment by ruankaodaren** [comment]
已经收到同学反馈的BUG，已经安排人员在测试验证了，修复后在同步

**Comment by ruankaodaren** [comment]
![1fecadb1090be22d9bef14126f2a9bd](https://github.com/user-attachments/assets/c5b58142-ffd3-442d-b219-2cd6a91be55a)
已优化交互，感谢提议。
