### ISSUE TITLE
PC端字体太小，是否可以增大字体！

### ISSUE THREAD

**Issue by satiling** [ruankaodaren/ruankao#21]
PC端字体太小，是否可以增大字体！看的眼睛很酸。

**Comment by forachange** [comment]
对，希望增加一个调节字体大小的功能，或者直接增大字体。 web 字体实在太小

**Comment by satiling** [comment]
什么时候可以字体变大啊？作者这个很好解决吧

**Comment by ruankaodaren** [comment]
国庆后会启动这个需求开发，到时候上线在回issue

**Comment by ruankaodaren** [comment]
已升级

**Comment by a55ure** [comment]
> 已升级
![image](https://github.com/user-attachments/assets/8577e4c8-97d3-49f0-aff0-a8f37661c54d)
选项字体大小可以变，但题目字体大小不变化

**Comment by a55ure** [comment]
> > 已升级
> > ![image](https://private-user-images.githubusercontent.com/67717024/374412249-8577e4c8-97d3-49f0-aff0-a8f37661c54d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjM2NTYsIm5iZiI6MTcyODM2MzM1NiwicGF0aCI6Ii82NzcxNzAyNC8zNzQ0MTIyNDktODU3N2U0YzgtOTdkMy00OWYwLWFmZjAtYThmMzc2NjFjNTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA0NTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjOTA0ODU3OGMyM2FjY2U0NTgyYWI1N2YzOTM5NGMwZTMxMmRkYTA5MDM3ZWM1MTVhNjI3NWIwNTkyMjk2MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IVgIXHvmbAJxzgBBfNiT6Zp1A3N-AQFQOKRdesP1d1Y)
> > 选项字体大小可以变，但题目字体大小不变化

![image](https://github.com/user-attachments/assets/79a64a2f-1656-4e1f-9b8d-120241a65cc6)
这个地方不对吧已经写死了
