### ISSUE TITLE
题目中有多个选项的时候，答题不知道是第几个

### ISSUE THREAD

**Issue by satiling** [ruankaodaren/ruankao#22]
考虑软件架构时，重要的是从不同的视角（perspective）来检查，这促使软件设计师考虑架构的不同属性。例如，展示功能组织的（ ）能判断质量特性，展示并发行为的（ ）能判断系统行为特性。选择的特定视角或视图也就是逻辑视图、进程视图、实现视图和（ ）。使用（ ）来记录设计元素的功能和概念接口，设计元素的功能定义了它本身在系统中的角色，这些角色包括功能、性能等。

这种题目，答题的时候根本不知道是第几个空格答题

**Comment by ruankaodaren** [comment]
有标注的，麻烦看一下截图。
![f2f7ca22d59dad58e6805d5d47d963a](https://github.com/user-attachments/assets/d9888e0b-4ee7-4e0e-8fc3-b6022fdd4502)

**Comment by satiling** [comment]
![Uploading Snipaste_2024-09-25_09-34-21.png…]()
![Uploading Snipaste_2024-09-25_09-34-09.png…]()

**Comment by satiling** [comment]
你看看，没有标注，在章节练习里面！

**Comment by satiling** [comment]
<img width="1439" alt="Snipaste_2024-09-25_09-34-21" src="https://github.com/user-attachments/assets/c4eed91b-4dca-4588-8951-1a404486cab9">
![Uploading Snipaste_2024-09-25_09-34-09.png…]()

**Comment by satiling** [comment]
在电脑端

**Comment by satiling** [comment]
在下面写看不清，能否在（）里面显示，没有的用（/）表示呢

**Comment by satiling** [comment]
字体能否增大些，看的不舒服，谢谢！

**Comment by satiling** [comment]
或者在每个（）中显示1/2/3/4，如果有的题目6个空格，根本找不过来，每次还要数数。非常不方便。

**Comment by ruankaodaren** [comment]
目前很多用户已经习惯用问题1-6表示了，我把需求反馈给产品，看他们如何优化，有结果在回issue
