### ISSUE TITLE
案例分析部分下方答案栏无法独立上下滚动 V2

### ISSUE THREAD

**Issue by 0xff06b5** [ruankaodaren/ruankao#29]
#10 还是之前的问题，我目前用下来问题并没有消失，另外在案例分析题目右边工具栏的“解析”按钮也不见了。

如果不好修的话是不是可以将桌面端改成垂直两栏排列？现在桌面显示器普遍都是宽屏，题目和答案在左右两侧排布可以更加有效利用显示面积，最重要的是两个垂直的独立滚动条应该更好调试

**Comment by ruankaodaren** [comment]
收到需求，我们这边测试一下，麻烦告知一下电脑分辨率
