### ISSUE TITLE
答题区希望可以支持下拉

### ISSUE THREAD

**Issue by DanYanShuYv4j** [ruankaodaren/ruankao#3]
![image](https://github.com/user-attachments/assets/552f0b1b-305e-49ee-9df2-8e32701a2cd6)
答题区无法移动导致无法直接查看图片整体。可以参考软考机考的页面设计

**Comment by ruankaodaren** [comment]
已经收到同学反馈的BUG，已经安排人员在测试验证了，修复后在同步

**Comment by ruankaodaren** [comment]
![1fecadb1090be22d9bef14126f2a9bd](https://github.com/user-attachments/assets/1f8635b9-4387-458c-999b-2c5c21ac3020)
已添加下拉功能，请同学使用。
