### ISSUE TITLE
历年真题 已全部完成的想重新查看会导致做题记录清空

### ISSUE THREAD

**Issue by Driss-Angel** [ruankaodaren/ruankao#30]
历年真题 已全部完成的点击"查看解析"或"练习"都会导致做题记录清空，"查看解析"能否保留做题记录。

![微信截图_20241010112227](https://github.com/user-attachments/assets/76b8cc34-a265-4f13-8e32-118e26eca671)

**Comment by ruankaodaren** [comment]
请点击“查看解析”、是否继续选着“继续”，就是保留做题记录的
