### ISSUE TITLE
系统架构师2023年的回忆版我有，发给你

### ISSUE THREAD

**Issue by satiling** [ruankaodaren/ruankao#31]
[Uploading 2023年11月系统架构设计师真题回忆版.pdf…]()

**Comment by satiling** [comment]
麻烦作者加入题库，谢谢

**Comment by ruankaodaren** [comment]
收到，最近几天安排入库

**Comment by ruankaodaren** [comment]
同学，文档没上传成功，能方便重新上传一份吗？

**Comment by satiling** [comment]
[2023年11月系统架构设计师真题回忆版.pdf](https://github.com/user-attachments/files/17410883/2023.11.pdf)

**Comment by satiling** [comment]
可以了？

**Comment by ruankaodaren** [comment]
可以了，感谢同学
