### ISSUE TITLE
【答案错误？】假设关系模式R(U，F)，属性集U={A，B，C}，函数依赖集F={A→B，B→C}。若将其分解为ρ={R1(U1，F1)，R2(U2，F2)}，其中U1={A，B}，U2={A，C}。那么，关系模式R、R1、R2分别达到了（ ）

### ISSUE THREAD

**Issue by javensun** [ruankaodaren/ruankao#32]
![image](https://github.com/user-attachments/assets/690495e1-bd64-428e-98c4-08468854375b)

F1∪F2 无法推出 F 中的 B->C 函数依赖。
所以答案应该是“无损连接但不保持函数依赖“ 吧？

**Comment by javensun** [comment]
若有群的话顺便求进群，一起学习。。

**Comment by ruankaodaren** [comment]
学习群暂时未开开放，后续重启再告知

**Comment by kuun993** [comment]
![Image](https://github.com/user-attachments/assets/563b67e2-9b71-40f6-a9e2-c8bf3ab32815)
