### ISSUE TITLE
题库里面的1.2计算机体系结构的1.2.2存储系统第18题的错别字

### ISSUE THREAD

**Issue by 24match** [ruankaodaren/ruankao#34]
磁盘阵列是由多台磁盘存储器组成的一个快速，大容量，高可靠的**外村子系统**，常见的磁盘阵列称为廉价冗余磁盘阵列(RAID)。

应该是外存子系统
![WX20241015-114652@2x](https://github.com/user-attachments/assets/943a2183-6504-4998-aa60-892dc9fbfa06)

**Comment by ruankaodaren** [comment]
已纠正，感谢反馈
