### ISSUE TITLE
聚焦丢失

### ISSUE THREAD

**Issue by zhihancn** [ruankaodaren/ruankao#36]
一个小小的问题，不知道算不算bug，先给大大反馈吧
点击上一题/下一题或者空白处时。题目高亮会丢失
<img width="710" alt="image" src="https://github.com/user-attachments/assets/2aef1c4c-7f8c-4557-ba6d-68966b127902">
正常状态下
<img width="456" alt="image" src="https://github.com/user-attachments/assets/8d546707-b86e-409b-9361-773ba3cd9868">

**Comment by ruankaodaren** [comment]
今天完成优化上线
