### ISSUE TITLE
在完成答卷后，先点击“查看解析”或“练习”，再点击“确定”后，已练习的记录被清空

### ISSUE THREAD

**Issue by yingmu6** [ruankaodaren/ruankao#40]
执行步骤：
1）完成历年真题中的某一套试题后，本意是想去看练习的记录。
2）点击“查看解析”或“练习”按钮，都会弹出提示框“该测试已完成,是否重新开始”，
      此时点击“重新开始”或“确定”，练习记录都会被清空，进入重新练习的状态。
3）这里的“确定”按钮就比较有歧义，应该在练习完成状态，改为“查看解析”，不用清空做题记录。

目前为了看做题的记录，只能从“做题记录”去查看，但是这个记录是零散的、有交叉的记录，不适合按某一个完整记录去看，比如看某一套试题的完整记录。所以使用起来比较麻烦。

**Comment by ruankaodaren** [comment]
收到反馈

**Comment by ruankaodaren** [comment]
今天优化上线
