### ISSUE TITLE
关于没做的题在算分时的处理

### ISSUE THREAD

**Issue by LuoYulin-OwO** [ruankaodaren/ruankao#42]
个人感觉没做的题在算分时应该按照错的来算，而不是被算成对的。

![image](https://github.com/user-attachments/assets/631b9150-9c76-474a-af54-238c0a0b27fb)

就比如这个，其实得分应该是45的不是嘛

**Comment by ruankaodaren** [comment]
收到同学反馈，已排期

**Comment by ruankaodaren** [comment]
错题 26
正确题 47
未答题 2
然后正确率  47/75

同学此计算模式没问题哦
