### ISSUE TITLE
顺序错乱导致二次查看不准确

### ISSUE THREAD

**Issue by sakurawztlt** [ruankaodaren/ruankao#43]
软考-中级-软件设计师，做完模拟考试时，同一个账号，在不同的电脑登录之后，本来答对的题就变错了，出现了，本来答对44道题，但是换了个电脑查看记录，就变成答对35道了，而且顺序也都打乱了，之前对的题也都变错了，但是按照原来选的abcd就是对的，疑似在打乱选择顺序时出错了

**Comment by ruankaodaren** [comment]
已修复BUG

**Comment by sakurawztlt** [comment]
修复好快，还招人嘛，一起维护
