### ISSUE TITLE
【新需求】调整模拟考试的题目的选择、顺序

### ISSUE THREAD

**Issue by tongjiann** [ruankaodaren/ruankao#8]
问题：
模拟考试里面的题目并不完整、连续

举个例子：
一个组题总共有5题，但是在模拟考试里面并不是连续的
1、可能是一道第一空的题目连着一道第三空的题目，
2、可能做到题目是第1空，做了十几道题目后遇到第2空的题目
3、可能只有其中部分空的题目，并没有所有的空

建议：将这种组题按顺序摆放在一起，便于做题的连贯思考

**Comment by ruankaodaren** [comment]
此类题我们正在优化，目前确实存在小部分此类题
