### ISSUE TITLE
【新需求】：每日一练以及智能训练题目数量选择

### ISSUE THREAD

**Issue by bijingyinwenjian** [ruankaodaren/ruankao#9]
1.每日一练每天都只能练一次。**（能否设置多次，以及设置题目数量由用户决定）**
2.智能训练**由用户来设置题目数量**。

**Comment by ruankaodaren** [comment]
1、每日练习可以多次练习，在做完页面有“重新做题”
2、“自主出题”就可以自己设置出题数，你可以试试此功能
